article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('serialize_article/',views.ArticleList.as_view()),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):

    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name ="Author" )
    title = models.CharField(max_length = 50,verbose_name = " Title ")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name=" Creation Date ")
    article_image = models.FileField(blank = True,null = True,verbose_name=" Add Photo to Article ")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "Name")
    comment_content = models.CharField(max_length = 200,verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.views import status
from .serializers import ArticleSerializer
from rest_framework import generics


class ArticleList(APIView):

    def get(self,request):
        article = Article.objects.all()
        serializer = ArticleSerializer(article, many=True)
        print('-----',serializer)
        print('----------',serializer.data)
        return Response(serializer.data)

    def post(self, request):
        pass


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})
    articles = Article.objects.all()

    return render(request, "articles.html", {"articles": articles})


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Article created successfully ")

        return redirect("article:dashboard")
    return render(request, "addarticle.html", {"form": form})


def detail(request, id):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id=id)
    print("article", article)
    comments = article.comments.all()

    return render(request, "detail.html", {"article": article, "comments": comments})


@login_required(login_url="user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    print("article---updateArticle", article)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request, " Article successfully updated ")
        return redirect("article:dashboard")

    return render(request, "update.html", {"form": form})


@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    print("article---deleteArticle", article)
    article.delete()

    messages.success(request, "Article Successfully Deleted ")

    return redirect("article:dashboard")


def addComment(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author, comment_content=comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail", kwargs={"id": id}))

templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>About us</h3>
<hr>



<h2>A product studio with an entrepreneurial spirit</h2>
<p>
We are data scientists and software craftsmen solving important business problems using a unique blend of business acumen, tech expertise and machine learning. We offer technology consulting, software development and ML expertise to YCombinator startups.

Parallel-y, we are also currently working on multiple inhouse products, many of which employ Machine Learning (a cutting edge Slack Standup bot, an applicant tracking and filtering tool, a geolocation chatting app and a Marketing Automation bot that aims to address marketing woes for startups).
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>
Create Article </h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">
Add Article </button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">
    
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Articles</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
        Published by {{article.author.username}}
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger"> Read more </a>
      <hr>
         
        </div>
      </div>
      </div>

{% endfor %}


{% else %}
<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
    No Articles Found
</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Control Board</h3>
<hr>
<p>

Welcome, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">
Add Article </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">
Title</th>
            <th scope="col">
Author</th>
            <th scope="col">
History</th>
            <th scope="col">
Update</th>
            <th scope="col">
Clear</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">
Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Clear</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    You have no articles yet...

</div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        Published by {{article.author.username}}

      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>Comments</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
        There are no comments to this article, be the first!
      </div>
      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">Add Comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter your name">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Add</button>
            </form>
          </div>
        </div>
        </div>
        
      </div>

      

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
        <h3>
                Welcome to the Veeresh Software Blog </h3>
        <p> As developers on this blog, you can share your blog posts and help people. </p>
</div>


<p>
        {% if request.user.is_authenticated %}
                Logged In, {{request.user.username}}
        {% else %}
                Not Logged In
        {% endif %}

</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Share Knowledge</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>
    

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Login </h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">
Login </button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3> Register </h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">
Login</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>
Update Article </h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger"> Update Article </button>
        </form>
    </div>
  </div>


{% endblock body %}